name: Manual Workflow
on:
    workflow_dispatch:
        inputs:
            environment:
                type: environment
                description: Choose your environment 
jobs:
    manual_job:
        name: My Manual Job 
        runs-on: ubuntu-latest
        environment:
            name: ${{ inputs.environment }}
        steps:
            - name: Print env name
              shell: bash 
              run: echo '${{ inputs.environment }}'
            - name: Use var and secret from env
              shell: bash 
              run: echo '${{ vars.USERNAME }}:${{ secrets.PASSWORD}}'

    get_target_env:
        name: Get target env 
        runs-on: ubunt-latest
        outputs: 
            target_env: ${{ steps.set_result.outputs.taret_env }}
        steps:
            - name: Set env based on branch
              id: set_results
              shell: bash 
              run: |
                echo "Branch: ${{ github.ref_name }}"
                echo "target_env=${{ github.ref_name}}" >> $GITHUB_OUTPUT