name: Upload Artifacts
on: [workflow_dispatch]
jobs:
    example-job:
        runs-on: ubuntu-latest
        steps:
            - name: Download a single artifact
              uses: actions/download-artifact@v4
              with:
                name: output-log-file